### ISSUE TITLE
Hide the dbg! macro output

### ISSUE THREAD

**Issue by akiirui** [Morganamilo/aur-depends#3]
https://github.com/Morganamilo/aur-depends/blob/50e954e6eab53a40dfb968bde5591004e2d9d023/src/resolve.rs#L481

Here have a `dbg!` macro output the `&aur_targets` information, but it shows in release build.

Maybe we can mark it with `#[cfg(build = "debug")]` or delete this line directly?

(I have a tested, delete this line not break the tests)

**Comment by Morganamilo** [comment]
It's just a debug print that was accidentally left in. Deleted.
