### ISSUE TITLE
Allow resolution of recursive deps

### ISSUE THREAD

**Issue by acxz** [Morganamilo/aur-depends#7]
This issue is a feature request to bring paru closer to feature parity with yay.

The particular feature is to allow the resolution of all deps (recursively) for a package. The original/downstream issue is https://github.com/Morganamilo/paru/issues/744.

Motivation and rationale is described in above linked issue.

**Comment by acxz** [comment]
@Morganamilo okay so I tried getting a bit familiar with this codebase and originally I was thinking I need to add say a `recursive_targets` function here:
https://github.com/Morganamilo/aur-depends/blob/29b53980ff9a9cdb2faa87d04f3c88f30e6d1bd5/src/base.rs#L134

so that it is exposed for paru to use.

But based on your earlier comments I need to add functionality in the resolver:
https://github.com/Morganamilo/aur-depends/blob/29b53980ff9a9cdb2faa87d04f3c88f30e6d1bd5/src/resolve.rs#L178

right?

Or would a function like `recursive_targets` be the exposed api for a function like `resolve_recrusive_deps` in resolve.rs?

**Comment by Morganamilo** [comment]
The dependency resolver is already recursive otherwise it wouldn't be a good dapondoncy solver. It's just smart enough to stop on already satisfied deps. All that's needed is a flag to tell it to not stop.

The local repo flag does a similarly thing so you can look for where that flag is checked to tell where you need to add checks.

**Comment by acxz** [comment]
@Morganamilo thanks for the advice on using a similar approach to the `LOCAL_REPO` flag.

Would something like this be a valid PR?

```diff
diff --git a/src/resolve.rs b/src/resolve.rs
index c0c6bb0..6cc4b8d 100644
--- a/src/resolve.rs
+++ b/src/resolve.rs
@@ -50,6 +50,8 @@ bitflags! {
         ///
         /// This means that we need to still build packages even if they are already installed.
         const LOCAL_REPO = 1 << 14;
+        /// Resolve all recursive dependencies.
+        const ALL_DEPS = 1 << 15;
     }
 }
 
@@ -1047,6 +1049,9 @@ impl<'a, 'b, E: std::error::Error + Sync + Send + 'static, H: Raur<Err = E> + Sy
 
     fn should_skip_aur_pkg(&self, dep: &Depend, is_target: bool) -> bool {
         if !is_target {
+            if !self.flags.contains(Flags::ALL_DEPS) {
+                return true;
+            }
             if !self.flags.contains(Flags::LOCAL_REPO) && self.satisfied_local(dep) {
                 return true;
             }
@@ -1260,7 +1265,8 @@ impl<'a, 'b, E: std::error::Error + Sync + Send + 'static, H: Raur<Err = E> + Sy
 
             for pkg in deps {
                 let dep = Depend::new(pkg);
-                if (!self.flags.contains(Flags::LOCAL_REPO)
+                if (!self.flags.contains(Flags::ALL_DEPS)
+                    && !self.flags.contains(Flags::LOCAL_REPO)
                     && self.find_repo_satisfier_silent(dep.to_string()).is_some()
                     && self.satisfied_local(&dep))
                     || self.find_repo_satisfier_silent(&pkg).is_some()
@@ -1324,7 +1330,8 @@ impl<'a, 'b, E: std::error::Error + Sync + Send + 'static, H: Raur<Err = E> + Sy
             for pkg in depends {
                 let dep = Depend::new(pkg.as_str());
 
-                if (!self.flags.contains(Flags::LOCAL_REPO)
+                if (!self.flags.contains(Flags::ALL_DEPS)
+                    && !self.flags.contains(Flags::LOCAL_REPO)
                     && self.find_repo_satisfier_silent(dep.to_string()).is_some()
                     && self.satisfied_local(&dep))
                     || self.find_repo_satisfier_silent(&pkg).is_some()
```

**Comment by Morganamilo** [comment]
That's basically where you want to make the changes but the conditions don't make sense.

```diff
         if !is_target {
+            if !self.flags.contains(Flags::ALL_DEPS) {
+                return true;
+            }
```

This for example will mean dependencies never get resolved. You can run the tests to see it break things.

**Comment by acxz** [comment]
Ah good catch!
Am testing the opposite now and all tests pass (`cargo test`). I'll go ahead and make a PR.

Thanks for your help!

**Comment by Morganamilo** [comment]
adae47712fa003bc0d234d355308dc5709fa69b3
